### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-core#183]
I just created this `docker-compose.yml` file for a member of the community to connect to the testnet. It might be useful for others.

```yml
version: "3.9"
services:
  hathor-core:
    image: hathornetwork/hathor-core
    command: run_node
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - /local/path/db/:/data
    environment:
      - HATHOR_TESTNET=true
      - HATHOR_STATUS=8080
      - HATHOR_STRATUM=8081
      - HATHOR_X_FAST_INIT_BETA=true
      - HATHOR_WALLET_INDEX=true
      - HATHOR_CACHE=true
      - HATHOR_CACHE_SIZE=100000
      - HATHOR_DATA=/data
      - HATHOR_ROCKSDB_STORAGE=true
      #- HATHOR_PEER=/data/peer.json
```
